ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_title TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_bio TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_topic_tags TEXT NOT NULL DEFAULT '';
